openapi: 3.0.0
info:
  title: exchange
  version: "1.0"
servers:
  - url: "http://localhost:8080"
paths:
  "/users/{userId}":
    parameters:
      - $ref: "#/components/parameters/userId"
    get:
      summary: get user
      tags: []
      responses:
        "200":
          $ref: "#/components/responses/getUser"
      operationId: get user
      description: get user.
      parameters: []
  "/users/{userId}/wallets":
    parameters:
      - $ref: "#/components/parameters/userId"
    get:
      summary: get user wallets
      tags: []
      responses:
        "200":
          $ref: "#/components/responses/getWallets"
      operationId: get user wallets
      description: get user wallets.
  "/users/{userId}/wallets/{walletId}":
    parameters:
      - $ref: "#/components/parameters/walletId"
      - $ref: "#/components/parameters/userId"
    get:
      summary: get user wallet
      tags: []
      responses:
        "200":
          $ref: "#/components/responses/getWallet"
      operationId: get user wallet
      description: get user wallet.
  /pairs:
    get:
      summary: get pairs
      tags: []
      responses:
        "200":
          $ref: "#/components/responses/getPairs"
      operationId: get pairs
      description: get pairs.
    parameters: []
  "/pairs/{pairId}":
    parameters:
      - $ref: "#/components/parameters/pairId"
    get:
      summary: get pair
      tags: []
      responses:
        "200":
          $ref: "#/components/responses/getPair"
      operationId: get pair
      description: get pair.
  "/pairs/{pairId}/orders":
    get:
      summary: get pair orders
      tags: []
      responses:
        "200":
          $ref: "#/components/responses/getOrders"
      operationId: get pair orders
      description: get pair orders.
    parameters:
      - $ref: "#/components/parameters/pairId"
    post:
      summary: create pair order
      operationId: create pair order
      responses:
        "200":
          $ref: "#/components/responses/getOrder"
      description: create pair order.
      requestBody:
        $ref: "#/components/requestBodies/createOrder"
  "/orders/{orderId}":
    parameters:
      - $ref: "#/components/parameters/orderId"
    get:
      summary: get order
      tags: []
      responses:
        "200":
          $ref: "#/components/responses/getOrder"
      operationId: get pair order
      description: get order.
    delete:
      summary: delete pair order
      operationId: delete pair order
      responses:
        "200":
          description: OK
      description: delete pair order.
components:
  schemas:
    user:
      title: user
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - id
        - name
    currency:
      title: currency
      type: object
      properties:
        id:
          type: string
        symbol:
          type: string
      required:
        - id
        - symbol
    pair:
      title: pair
      type: object
      properties:
        id:
          type: string
        keyCurrency:
          $ref: "#/components/schemas/currency"
        settlementCurrency:
          $ref: "#/components/schemas/currency"
      required:
        - id
        - keyCurrency
        - settlementCurrency
    wallet:
      title: wallet
      x-stoplight:
        id: we8hbida957cp
      type: object
      properties:
        id:
          type: string
        currency:
          $ref: "#/components/schemas/currency"
        amount:
          type: integer
      required:
        - id
        - currency
        - amount
    order:
      title: order
      x-stoplight:
        id: 487uqa23jwpzi
      type: object
      properties:
        id:
          type: string
        pair:
          $ref: "#/components/schemas/pair"
        keyAmount:
          type: integer
        settlementAmount:
          type: integer
        utcCreatedAt:
          type: string
          format: date-time
      required:
        - id
        - pair
        - keyAmount
        - settlementAmount
        - utcCreatedAt
    orderPosition:
      type: string
      title: orderPosition
      x-stoplight:
        id: mpsn3pazvzoze
      enum:
        - BUY
        - SELL
      description: order position enum
  securitySchemes: {}
  responses:
    getUser:
      description: get user response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/user"
    getWallet:
      description: get wallet response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/wallet"
    getWallets:
      description: get wallets response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/wallet"
    getPairs:
      description: get pairs response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/pair"
    getPair:
      description: get pair response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/pair"
    getOrder:
      description: get order response
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                $ref: "#/components/schemas/order"
    getOrders:
      description: get orders response
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: array
                items:
                  $ref: "#/components/schemas/order"
  requestBodies:
    createOrder:
      content:
        application/json:
          schema:
            type: object
            properties:
              key_amount:
                type: integer
              settlement_amount:
                type: integer
              position:
                $ref: "#/components/schemas/orderPosition"
              pair:
                $ref: "#/components/schemas/pair"
            required:
              - key_amount
              - settlement_amount
              - position
              - pair
      description: create order request body
  parameters:
    userId:
      name: userId
      in: path
      schema:
        type: string
      description: user id
      required: true
    walletId:
      name: walletId
      in: path
      required: true
      schema:
        type: string
      description: wallet id
    pairId:
      name: pairId
      in: path
      required: true
      schema:
        type: string
      description: pair id
    orderId:
      name: orderId
      in: path
      required: true
      schema:
        type: string
      description: order id
